services:
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: arbitary-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - TZ=${TZ:?err}
      - UPLOAD_LIMIT=900M
    ports:
      - '${PORT:?err}:80'
    # networks:
    #   - some_database_server_network
# networks:
#   some_database_server_network:
#     external: true